import { contextBridge, ipcRenderer } from 'electron';
import type { IpcChannel, PushChannel } from '../shared/ipc-contract.js';

const allowedInvokeChannels = new Set<string>([
  'workspace:list',
  'workspace:create',
  'workspace:update',
  'workspace:delete',
  'workspace:reorder',
  'profile:list',
  'profile:create',
  'profile:update',
  'profile:delete',
  'service:list',
  'service:create',
  'service:update',
  'service:delete',
  'service:reorder',
  'service:reload',
  'service:navigateBack',
  'service:navigateForward',
  'service:navigate',
  'service:sleep',
  'service:wake',
  'service:openExternal',
  'service:currentUrl',
  'service:clearStorage',
  'service:setZoom',
  'service:find',
  'service:stopFind',
  'view:setBounds',
  'view:focus',
  'tab:list',
  'tab:create',
  'tab:close',
  'tab:setActive',
  'recipe:catalog',
  'recipe:createCustom',
  'recipe:updateCustom',
  'recipe:deleteCustom',
  'recipe:resolveForInstance',
  'registry:search',
  'registry:validate',
  'registry:import',
  'registry:stats',
  'linkRule:list',
  'linkRule:upsert',
  'linkRule:delete',
  'linkRule:test',
  'dashboard:list',
  'dashboard:upsert',
  'dashboard:delete',
  'dashboard:snapshot',
  'dashboard:saveSession',
  'shortcut:list',
  'shortcut:upsert',
  'shortcut:delete',
  'permission:list',
  'permission:upsert',
  'permission:delete',
  'download:list',
  'download:open',
  'download:clear',
  'migration:preview',
  'migration:run',
  'trust:status',
  'performance:status',
  'automation:list',
  'automation:upsert',
  'automation:delete',
  'automation:test',
  'focusMode:list',
  'focusMode:upsert',
  'focusMode:delete',
  'focusMode:status',
  'browserImport:preview',
  'browserImport:run',
  'recipeStudio:analyze',
  'recipeStudio:create',
  'extensionPack:list',
  'extensionPack:apply',
  'firewall:list',
  'firewall:upsert',
  'firewall:delete',
  'firewall:test',
  'snapshot:list',
  'snapshot:create',
  'snapshot:restore',
  'snapshot:delete',
  'analytics:personal',
  'portable:status',
  'portable:configure',
  'peerSync:status',
  'peerSync:upsert',
  'peerSync:delete',
  'workKit:list',
  'workKit:apply',
  'layout:get',
  'layout:set',
  'lock:status',
  'lock:setup',
  'lock:unlock',
  'lock:lock',
  'sync:status',
  'sync:configure',
  'sync:join',
  'sync:exportVault',
  'sync:importVault',
  'sync:now',
  'task:list',
  'task:create',
  'task:update',
  'task:delete',
  'task:reorder',
  'palette:query',
  'notification:list',
  'notification:search',
  'notification:markRead',
  'notification:markAllRead',
  'notification:snooze',
  'notification:clear',
  'notification:unreadCount',
  'ai:status',
  'ai:configure',
  'ai:clearKey',
  'ai:brief',
  'ai:triage',
  'aiPrompt:list',
  'aiPrompt:upsert',
  'aiPrompt:delete',
  'aiPrompt:run',
  'aiPrompt:extractTasks',
  'extension:list',
  'extension:add',
  'extension:remove',
  'extension:setEnabled',
  'import:ferdium',
  'metrics:get',
  'settings:get',
  'settings:set',
  'update:status',
  'update:check',
  'update:install',
  'account:status',
  'account:signup',
  'account:login',
  'account:logout',
  'account:syncNow'
]);
const allowedPushChannels = new Set<string>([
  'event:unread',
  'event:notification-clicked',
  'event:service-state',
  'event:locked',
  'event:data-changed',
  'event:notification',
  'event:update-status',
  'event:settings-changed'
]);

const api = {
  invoke(channel: IpcChannel, payload?: unknown): Promise<unknown> {
    if (!allowedInvokeChannels.has(channel)) {
      return Promise.reject(new Error(`Blocked IPC channel: ${channel}`));
    }
    return ipcRenderer.invoke(channel, payload);
  },
  on(channel: PushChannel, callback: (payload: unknown) => void): () => void {
    if (!allowedPushChannels.has(channel)) {
      throw new Error(`Blocked push channel: ${channel}`);
    }
    const listener = (_event: Electron.IpcRendererEvent, payload: unknown): void =>
      callback(payload);
    ipcRenderer.on(channel, listener);
    return () => ipcRenderer.removeListener(channel, listener);
  }
};

contextBridge.exposeInMainWorld('appdeck', api);

export type AppDeckBridge = typeof api;
