/**
 * The single source of truth for IPC channel names, split from the zod contract so the sandboxed
 * preload bridge can import it without pulling zod into the preload bundle (externalized deps are
 * unavailable to a sandboxed preload). `ipcSchemas` in ipc-contract.ts is checked against this
 * list at compile time, so the two cannot drift.
 */
export const invokeChannels = [
  'workspace:list',
  'workspace:create',
  'workspace:update',
  'workspace:delete',
  'workspace:reorder',
  'profile:list',
  'profile:create',
  'profile:update',
  'profile:delete',
  'service:list',
  'service:create',
  'service:update',
  'service:delete',
  'service:reorder',
  'service:reload',
  'service:navigateBack',
  'service:navigateForward',
  'service:sleep',
  'service:wake',
  'service:openExternal',
  'service:currentUrl',
  'service:clearStorage',
  'service:setZoom',
  'service:find',
  'service:stopFind',
  'service:pendingCustomCode',
  'service:approveCustomCode',
  'view:setBounds',
  'view:focus',
  'tab:list',
  'tab:create',
  'tab:close',
  'tab:setActive',
  'recipe:catalog',
  'recipe:createCustom',
  'recipe:resolveForInstance',
  'registry:search',
  'registry:validate',
  'registry:import',
  'registry:stats',
  'linkRule:list',
  'linkRule:upsert',
  'linkRule:delete',
  'linkRule:test',
  'dashboard:list',
  'dashboard:upsert',
  'dashboard:delete',
  'dashboard:snapshot',
  'dashboard:saveSession',
  'shortcut:list',
  'shortcut:upsert',
  'shortcut:delete',
  'permission:list',
  'permission:upsert',
  'permission:delete',
  'download:list',
  'download:open',
  'download:clear',
  'migration:preview',
  'migration:run',
  'trust:status',
  'trust:updateBlocklist',
  'performance:status',
  'automation:list',
  'automation:upsert',
  'automation:delete',
  'automation:test',
  'focusMode:list',
  'focusMode:upsert',
  'focusMode:delete',
  'focusMode:status',
  'focusMode:activate',
  'browserImport:preview',
  'browserImport:run',
  'recipeStudio:analyze',
  'recipeStudio:create',
  'extensionPack:list',
  'extensionPack:apply',
  'firewall:list',
  'firewall:upsert',
  'firewall:delete',
  'firewall:test',
  'snapshot:list',
  'snapshot:create',
  'snapshot:restore',
  'snapshot:delete',
  'analytics:personal',
  'repair:status',
  'repair:run',
  'portable:status',
  'peerSync:status',
  'peerSync:upsert',
  'peerSync:sync',
  'peerSync:delete',
  'workKit:list',
  'workKit:apply',
  'layout:get',
  'layout:set',
  'lock:status',
  'lock:setup',
  'lock:unlock',
  'lock:lock',
  'sync:status',
  'sync:configure',
  'sync:join',
  'sync:now',
  'task:list',
  'task:create',
  'task:update',
  'task:delete',
  'palette:query',
  'notify:incoming',
  'unread:report',
  'notification:list',
  'notification:markSeen',
  'notification:lastSeen',
  'notification:search',
  'notification:markRead',
  'notification:markAllRead',
  'notification:snooze',
  'notification:clear',
  'notification:unreadCount',
  'ai:status',
  'ai:configure',
  'ai:clearKey',
  'ai:brief',
  'ai:triage',
  'ai:draftReply',
  'ai:suggestMutes',
  'aiPrompt:list',
  'aiPrompt:upsert',
  'aiPrompt:delete',
  'aiPrompt:run',
  'aiPrompt:extractTasks',
  'aiRun:list',
  'extension:list',
  'extension:add',
  'extension:remove',
  'extension:setEnabled',
  'import:ferdium',
  'metrics:get',
  'settings:get',
  'settings:set',
  'update:status',
  'update:check',
  'update:install',
  'account:status',
  'account:signup',
  'account:login',
  'account:logout',
  'account:syncNow'
] as const;

export type IpcChannel = (typeof invokeChannels)[number];

/** Invoked directly by the service preload over ipcRenderer; never exposed to the renderer bridge. */
export const serviceOnlyInvokeChannels = ['notify:incoming', 'unread:report'] as const;

export type ServiceOnlyInvokeChannel = (typeof serviceOnlyInvokeChannels)[number];

/** Every channel the renderer bridge may invoke — the contract minus service-only channels. */
export const rendererInvokeChannels: readonly IpcChannel[] = invokeChannels.filter(
  (channel) => !(serviceOnlyInvokeChannels as readonly string[]).includes(channel)
);

export const pushChannels = [
  'event:unread',
  'event:notification-clicked',
  'event:service-state',
  'event:locked',
  'event:data-changed',
  'event:notification',
  'event:update-status',
  'event:settings-changed',
  'event:custom-code-pending',
  'event:ai-run',
  'event:views-resync-requested',
  'event:workspace-open-requested',
  'event:focus-mode-requested'
] as const;

export type PushChannel = (typeof pushChannels)[number];
